### ISSUE TITLE
Can't support .onAppear, .animation, .overlay ?

### ISSUE THREAD

**Issue by rajaslucky89** [skiptools/skip-ui#10]
why **skip** not support `.onAppear {}`, `.animation(.easeInOut(duration: 1.3), value: splashScreen)` and `.overlay` ?

**Comment by aabewhite** [comment]
We simply haven't gotten to these modifiers yet! Note that you can use .task to a lot of the things .onAppear can do. And you can use unsupported modifiers for your iOS app with #if !SKIP. They just won't appear in your Android app.

`SomeView()
    #if !SKIP
    .animation(...)
    #endif
`

**Comment by aabewhite** [comment]
.onAppear is now supported

**Comment by aabewhite** [comment]
.overlay is also supported, and .animation is on our radar
