### ISSUE TITLE
EmptyView inside Form renders empty row

### ISSUE THREAD

**Issue by pnewell** [skiptools/skip-ui#15]
If you put an EmptyView inside a Form in skip-ui, it will render an empty section while in SwiftUI it does not render anything (expected behavior).

**Steps to recreate:**
1. New app with following ContentView body
```
Form {
    Text("Text")
    EmptyView()
}
```

**iOS behavior:**
Single row with Text

**Android behavior:**
Row with text and another empty row

**Priority:**
Medium: EmptyView() is frequently used with switch statements and is needed for cases where you don't want anything to show at all.

**Workaround:**
```
Form {
    Text("Text")
    #if !SKIP
    EmptyView()
    #else
    // SKIP INSERT: {}
    #endif
}
```

**Comment by aabewhite** [comment]
Should be fixed in skip-ui 0.3.21
