### ISSUE TITLE
Is Searchable not yet implemented?

### ISSUE THREAD

**Issue by cleamaec** [skiptools/skip-ui#17]
Hi! Is the searchable method for NavigationStack not yet implemented?

```
NavigationStack {
    ...
}
.searchable(text: $searchText)
```

Above code is throwing these errors: `Unresolved reference: searchable` and `Skip is unable to match this API call to determine whether it results in a View. Consider adding additional type information`

**Comment by aabewhite** [comment]
Note that we're currently focused on list-related operations (we recently introduced support for editActions, and are currently implementing onDelete and onMove), and searchable is on our short list of high priority functions to investigate

**Comment by aabewhite** [comment]
Added in skip-ui 0.3.25. Use File->Packages->Update to Latest Package Versions to update your Xcode packages.

Does not yet support search scopes or displaying a list of search suggestions.
