### ISSUE TITLE
Textfield type keyboardType not supported yet

### ISSUE THREAD

**Issue by aulimge** [skiptools/skip-ui#18]
<img width="1047" alt="Screenshot 2023-11-24 at 11 01 39 PM" src="https://github.com/skiptools/skip/assets/30146547/d3d01f8a-9d30-4a02-adb7-ae03152e30ab">

**Comment by aabewhite** [comment]
Added in skip-ui 0.3.25. Use File->Packages->Update to Latest Package Versions to update your Xcode packages.
