### ISSUE TITLE
How to customize Textfeild ?

### ISSUE THREAD

**Issue by X901** [skiptools/skip-ui#24]
Hi, 
I tried to customize Textfield

```  
TextField("", text: .constant("Text"))
                        .textFieldStyle(.plain)
                        .padding(5.0)
                        .background(RoundedRectangle(cornerRadius: 5.0)
                            .fill(Color.white))
                        .padding(.horizontal, 10)
                        .overlay(
                            RoundedRectangle(cornerRadius: 5.0)
                                .stroke(.gray, lineWidth: 1.0)
                                .padding(.horizontal, 10.0)
                           )
```
                           But I got alot of errors
                           

**horizontal:**

`Skip is unable to determine the owning type for member 'horizontal'. Add the owning type (e.g. MyType.horizontal)`
                  
**textFieldStyle :**

`This API is not yet available in Skip. Consider filing an issue against the owning library at https://github.com/skiptools, or see the library README for information on adding support`

**overlay:**

`Skip is unable to match this API call to determine whether it results in a View. Consider adding additional type information`

**Comment by aabewhite** [comment]
Added support for TextStyle.plain in SkipUI 0.4.2
