### ISSUE TITLE
ForEach on numeric range always starts with 0

### ISSUE THREAD

**Issue by marcprux** [skiptools/skip-ui#25]
Regardless of the starting range of a `ForEach`, the index always starts with 0.

```swift
List {
    ForEach(5..<10) { i in
        NavigationLink("Item #\(i)", value: i)
    }
}
```

<img width="353" alt="Screenshot 2024-01-14 at 09 54 27" src="https://github.com/skiptools/skip-ui/assets/659086/a9f2ac6c-d999-4d75-8bb2-a5899ddbe525">
<img width="310" alt="Screenshot 2024-01-14 at 09 54 35" src="https://github.com/skiptools/skip-ui/assets/659086/eb9c2372-b518-4c11-b660-36d7078df37d">

**Comment by aabewhite** [comment]
Fixed in 0.4.2
