### ISSUE TITLE
Frame maxWidth disparity...

### ISSUE THREAD

**Issue by jeffc-dev** [skiptools/skip-ui#29]
There seems to be a disparity in how Android handles view frame `maxWidth` as compared to SwiftUI.

When applying the `frame` modifier to a `Text` (with a black border to make it show up) with `maxWidth` set to `.infinity`, the SwiftUI view will expand to fill its parent, whereas the Android equivalent won't. This *also* seems to happen with `VStack`, `HStack`, etc.

A quick modification of Skip's basic app template shows this in action:

```
VStack(spacing: 0) {
    Text("Hello \(name)!")
        .frame(maxWidth: .infinity)
        .border(Color.black)
}
.font(.largeTitle)
.tabItem { Label("Welcome", systemImage: "heart.fill") }
.tag(Tab.welcome)

```

Is this a known issue, and if so are such frame/layout quirks documented anywhere? It seems like it'd come up pretty often.

Does anybody know of a workaround to achieve the same behavior on both platforms?

The screenshot below shows the same view in both the iOS Simulator and in qemu.

<img width="1056" alt="Screenshot 2024-05-01 at 7 32 51 PM" src="https://github.com/skiptools/skip-ui/assets/24899648/d3e6faee-a0dd-4de0-b78b-05c0b646a657">

**Comment by aabewhite** [comment]
Thank you for the report!

We've reproduced the issue and are preparing a fix. We'll respond here when it is available.

**Comment by aabewhite** [comment]
The issue should be fixed in skip-ui 0.8.3. Use Xcode's File->Packages->Update to Latest to get it.

Sorry for the trouble, and please let us know if you run into any additional issues.

**Comment by aabewhite** [comment]
Providing a non-zero min and infinity max is a known issue. I’ll take another crack at it later today, though, and let you know if I’m able to improve the behavior. Thanks again for the feedback - keep it coming! Sent from my iPhoneOn May 2, 2024, at 3:31 AM, Jeff ***@***.***> wrote:﻿
Thanks for the quick fix, Abe! I really appreciate it.
Using the following seems to work great now:
Text("Test")
    .frame(maxWidth: .infinity)
    .border(Color.black)

I did notice, however, that if a minWidth is supplied there is still a disparity - It shrinks things down in Compose but expands to the full width in SwiftUI.
Text("Test")
    .frame(minWidth: 10.0, maxWidth: .infinity)
    .border(Color.black)

This is sufficient for my use case, I think, but I thought you might want to know.
Thanks again!

**Comment by aabewhite** [comment]
I tweaked the layout behavior in the min=value + max=infinity case in the latest skip-ui version. I also documented a known remaining issue here:
https://github.com/skiptools/skip-ui/blob/main/README.md#layout
