### ISSUE TITLE
Support SwiftUI `View.modifier`

### ISSUE THREAD

**Issue by marcprux** [skiptools/skip-ui#3]
### Discussed in https://github.com/skiptools/skip/discussions/32

<div type='discussions-op-text'>

<sup>Originally posted by **shial4** November  3, 2023</sup>
Please add support for SwiftUI Views modifier to pass custom modifier class in
Along with custom modifiers build of `ViewModifier`

I would love to SKIP enable this framework 
https://github.com/shial4/SwiftUIComponents/blob/main/Sources/SwiftUIComponents/Components/ViewModifiers/FrameModifier.swift

```
.modifier(FrameModifier(
         offset: CGSize(width: 10, height: 20),
         rotation: Angle(degrees: 45),
         scale: CGSize(width: 2, height: 2),
         anchor: .center)
     )
```
</div>

**Comment by aabewhite** [comment]
Done
