### ISSUE TITLE
.onChange with brackets form results in compilation error

### ISSUE THREAD

**Issue by hepspl** [skiptools/skip-ui#31]
`.onChange()` is marked as fully supported however I noticed that at least one form of `onChange` results in compilation error:

`
		.onChange(of: someVar, { oldValue, newValue in
                               ...
		})
`
Will result in 
> Cannot infer a type for this parameter. Please specify it explicitly.

Transforming it into:
`
		.onChange(of: someVar) { oldValue, newValue in
                               ...
		}
`
Fixes the problem.

Please consider checking while other form does not work and produce kind of misleading error message.

**Comment by aabewhite** [comment]
Thanks! We'll look into this!

**Comment by aabewhite** [comment]
This should be fixed now in SkipUI 0.9.2. Use Xcode's File->Packages->Update to Latest to get the fixed version. Please let us know if you have any issues, and thanks again for the report.

**Comment by hepspl** [comment]
Thank you for your quick support!
