### ISSUE TITLE
Date / timepicker layout issue

### ISSUE THREAD

**Issue by J05HI** [skiptools/skip-ui#39]
Using the date or timepicker in landscape mode has the following issue:

![Screenshot_20240627-120138.png](https://github.com/skiptools/skip-ui/assets/16399787/8393327a-5114-44a5-9aee-e2a625d37c4c)

![Screenshot_20240627-120130.png](https://github.com/skiptools/skip-ui/assets/16399787/dd700392-1866-4ed8-acf5-157e9ddff89c)

It should look like that (example from Google Calendar app):

![Screenshot_20240627-120232.png](https://github.com/skiptools/skip-ui/assets/16399787/74467cd8-b897-4ed1-b0a2-f319999d24b1)

![Screenshot_20240627-120216.png](https://github.com/skiptools/skip-ui/assets/16399787/2435e76a-72bd-426a-9a78-1d523b963c1a)

**Comment by aabewhite** [comment]
Thanks for the report! I wasn't able to get the layouts pictured, but I did improve the behavior of our date and time pickers in landscape a bit in skip-ui 0.10.2
