### ISSUE TITLE
Support `.frame(maxWidth: Double.infinity)`

### ISSUE THREAD

**Issue by marcprux** [skiptools/skip-ui#4]
### Discussed in https://github.com/skiptools/skip/discussions/33

<div type='discussions-op-text'>

<sup>Originally posted by **shial4** November  3, 2023</sup>
I know frame `maxWidth` and `maxHeight` is low priority for you, however, I've been doing SwiftUI since the very beginning and have many apps build with it. 
I find this `frame` modifier very powerful and would love to have it fully supported by SKIP 
```
.frame(maxWidth: Double.infinity)
```
</div>

**Comment by aabewhite** [comment]
In progress...

**Comment by aabewhite** [comment]
Pushed
