### ISSUE TITLE
Custom Alert Dialog

### ISSUE THREAD

**Issue by J05HI** [skiptools/skip-ui#42]
Why is a custom alert used here?
Why not just use the official Compose equivalent: [https://www.composables.com/material3/alertdialog](https://www.composables.com/material3/alertdialog)

![Screenshot_20240827-182232.png](https://github.com/user-attachments/assets/8d455eb3-f57f-4f16-93ec-ca766c9a12ef)

**Comment by aabewhite** [comment]
Unfortunately the Compose function doesn't support some of the things that iOS alerts allow, such as more than two buttons. So we had the choice of making alerts that would use the default in some cases but not in others, or going with a custom but always consistent design. We chose the latter. 

It should be possible to call the Compose function using ComposeView if you like
